server:
  port: 9000

spring:
  data:
    redis:
      host: localhost
      port: 26379
      database: 0
  cloud:
    gateway:
      routes:
        - id: all
          uri: http://localhost:8080
          predicates:
            - Path=/**
          filters:
#            - name: RequestRateLimiter
            - name: CustomRedisRateLimitFilter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 100
                redis-rate-limiter.requestedTokens: 3
                key-resolver: "#{@userIdAsKeyResolver}"
#  redis:
#    host: localhost
#    port: 26379
#    database: 0
#logging:
#  level:
#    root: debug